---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Set variables from defaults
  set_fact:
     uwsgi_bin_path: '{{ uwsgi_bin_path|default(__uwsgi_bin_path) }}'

- name: Setup uwsgi apps
  include: one-app.yml
  with_items: '{{ uwsgi_apps }}'
  loop_control:
    loop_var: _uwsgi_app

- meta: flush_handlers

- name: Start applications
  service:
    name: 'uwsgi-{{ item.name }}'
    state: started
    enabled: true
  with_items: '{{ uwsgi_apps }}'